[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "smart-object-tracking"
version = "0.1.0"
description = "Smart Object Tracking System"


[tool.setuptools.packages.find]
where = ["src"]
